### ISSUE TITLE
Holographics are blocking physicial and blocks you.

### ISSUE THREAD

**Issue by master4life** [DRE2N/HolographicMenus#13]
I Just found out that the menu is physicial and can push out other entities around.

Demo: https://streamable.com/a5ooq

**Comment by Sataniel98** [comment]
Yes, I noticed that also. I'll try to get that fixed before the new version gets released, but I'll need to do some research to see if it's possible to make them not collidable while keeping them touchable and if this behavior is intended by the provider (HolographicDisplays).

**Comment by Sataniel98** [comment]
Doesn't seem to be possible, sorry :C I'll close this until I find a way to fix it.
