### ISSUE TITLE
Players can't see the buttons

### ISSUE THREAD

**Issue by saintdevin** [DRE2N/HolographicMenus#14]
Players can't see the buttons in a menu unless I Op them. They have perms to open the menu and when they do they only see the name of the menu. If you have any idea on how to fix this please let me know, I'm currently working on reviving an old SAO server with some of the old staff and we would love to use this plugin.  Also it seems that if menus are made public you can use another player's menu.

**Comment by Sataniel98** [comment]
If menus are public, they are by design not attached to a player and can therefore be used by anyone. I guess your problem is caused by per button permissions. I'd need to see your permission setup for Holographic Menus and your menu script.

**Comment by saintdevin** [comment]
wait there are permissions for buttons too? I didn't see anything about that. I may have overlooked it.

**Comment by Sataniel98** [comment]
Not necessarily. You could just leave this option out. But I guess if you copy / pasted the wiki example 1:1, you might have missed removing or changing it.

```
        # The permission a player needs to see the button.
        permission: menu.click
```

But I don't know, as I said, I can't help you if you don't provide the necessary info about your setup ^^

**Comment by saintdevin** [comment]
sorry xD I just saw it right before i checked back here. thank you though. I feel so stupid for missing that

**Comment by Sataniel98** [comment]
No problem, I guess I'll add a troubleshooting or FAQ article to the wiki to clarify that. It's sometimes hard to emphathize with a user and to guess what can be missed, as a developer, so thanks for that ^^

**Comment by saintdevin** [comment]
ok I found out that if players are in a plot wolrd made with plotsquared they can't use the menu buttons there, May be a good idea to warn people about that too. they can only do it if they are added to the plot. Guessing it works like that since it uses an armor stand?

**Comment by Sataniel98** [comment]
Yes. I could argue that's an issue on the end of the protection plugin, or Holographic Displays because the holograms' touch handlers aren't invoked. But I'll try to find a reasonable way to bypass that on my end.

**Comment by Sataniel98** [comment]
See #15
