### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by BlindMag** [DRE2N/HolographicMenus#16]
Would it be possible to not have the hologram move while the player isn't actually walking? I'm asking because when the user goes to shift to press a button the whole menu jolts and they sometimes misclick.

**Comment by BlindMag** [comment]
It's also a bit close, is there anyway we could set the distance away from the players? If not would you be able to add support to make it spawn a further distance away?

**Comment by BlindMag** [comment]
Also, if the user walks away while it does not follow does it despawn after awhile?

**Comment by Sataniel98** [comment]
Quoting from the wiki...
1.
```
# How many degrees a player may turn until the menu follows the movement.
# This is useful if you have buttons that use an X value higher or lower than 0.
# If you do not use buttons that do so, the rotation tolerance should be set to 0
# because lower values lead to noticeably smoother movement.
rotationTolerance: 25
```

2.
```
# The distance between the player's location and where the button shall appear.
distance: 1.75
```

3. It will despawn when the player leaves or opens a new menu.

**Comment by BlindMag** [comment]
Thank you so much, I appreciate the response, you know I didn't even see those options at the bottom! :) I am completely blind apparently.
