### ISSUE TITLE
High speed glitch

### ISSUE THREAD

**Issue by Elytes** [DRE2N/HolographicMenus#21]
Hi !
I discovered a glitch, we can run really fast by putting the menu behind us and runnig, cause the menu will push us, do you have any idea how we can fix it ?

**Comment by Sataniel98** [comment]
Menus can't be non-physical unfortunately. If they were, you couldn't click them. The best workaround is to modify the distance between the player and the menu:
```
# The distance between the player's location and where the button shall appear.
distance: 1.75
```

**Comment by Elytes** [comment]
Thanks for your reply, I just saw that too and I put it to distance: 3.00 and it works perfectly, thanks :)
