### ISSUE TITLE
Question: Keeping holograms open forever

### ISSUE THREAD

**Issue by bijanmahdavi** [DRE2N/HolographicMenus#22]
Hello, i might be missing something but when i try to issue the command /hm [playername] permamenu [name of menu]
the menu opens, is publicly visable, and does not move, but when that player logs out, the menu goes away. Is there a way to keep a menu open forever at a specific location? Thank you!

**Comment by Sataniel98** [comment]
The command to open menus persistently is /hm openPermanently [name of menu].

**Comment by bijanmahdavi** [comment]
@Sataniel98 awesome, how would i go about closing one of these menus that got opened permanently?

**Comment by Sataniel98** [comment]
A permanently opened instance of the menu is practically a configuration value like everything else so you'd remove it from the file.

**Comment by bijanmahdavi** [comment]
Thank you very much!
