### ISSUE TITLE
"The menu main does not exist" 

### ISSUE THREAD

**Issue by Zanadude** [DRE2N/HolographicMenus#26]
Hello Sataniel, I hope all is well during these times of pandemic.
I've been working on a server in which can use this plugin. I'm currently having an issue in which when I use /m under my default group(GroupManager Plugin) It says this "The menu **main** does not exist". 

My default rank uses these permissions
    - holographicmenus.menu
    - holographicmenus.menu.main
    - holographicmenus.menu.button(1-5) although I'm not sure if that is the format

The title of the menu file is main.yml it is located within the menus folder 
[main.yml contents] (i will also list the config.yml contents further below)

type: PRIVATE
followingOnMove: true
menuPages:
  1:
    buttons:
      1:
        label: "&f[ &2Skyblock&f Island ]"
        type: BUTTON
        command: "island"
        variableMessages:
        closeMenu: true
        permission: menu.button1
        x: 0.0
        y: 0.4
      2:
        label: "&f[ &2CaveBlock&f Island ]"
        type: BUTTON
        command: "cave"
        variableMessages:
        closeMenu: true
        permission: menu.button2
        x: 0.0
        y: 0.1
      3:
        label: "&f[ &2Acid&f Island ]"
        type: BUTTON
        command: "ai"
        variableMessages:
        closeMenu: true
        permission: menu.button3
        x: 0.0
        y: -0.2
      4:
        label: "&f[ &2Skygrid&f World ]"
        type: BUTTON
        command: "Skygrid"
        variableMessages:
        closeMenu: true
        permission: menu.button4
        x: 0.0
        y: -0.5
      5:
        label: "&f[ &6Infinite &fParkour ]"
        type: BUTTON
        command: "witp join"
        variableMessages:
        closeMenu: true
        permission: menu.button5
        x: 0.0
        y: -0.8

staticButtons:
  1:
    item: "INK_SACK:4"
    type: TITLE
    x: 0.0
    y: 1.8
  2:
    label: "&6&lGAMEMODE &e&lMENU"
    type: TITLE
    x: 0.0
    y: 0.7
  3:
    label: "&a[CLOSE]"
    type: BUTTON
    sound: ui.button.click
    closeMenu: true
    x: 0.0
    y: -1.10
distance: 1.75
rotationTolerance: 25

[Config.yml Contents]

configVersion: 0
language: english
mainMenu: main

The menu is found and works when the user is an operator
Any help would be appreciated, cheers!

**Comment by Zanadude** [comment]
Hey, turns out it was just groupmanager, I migrated to Luckperms and everything's working! Thanks for the excellent plugin.

**Comment by Sataniel98** [comment]
Glad to hear it's resolved. I'm fine so far and hope you're too. Let me know if you have other problems :)
