### ISSUE TITLE
Public Menu command not working

### ISSUE THREAD

**Issue by BubblesIsEpic** [DRE2N/HolographicMenus#27]
I am trying to open a public menu doing /m op main (main being the name of the menu) and it states "The menu main does not exist"

**Comment by Sataniel98** [comment]
Do you have permission to use the menu?

**Comment by BubblesIsEpic** [comment]
yes

**Comment by Sataniel98** [comment]
And it's set to PUBLIC?

**Comment by BubblesIsEpic** [comment]
Ah I am a bing bong, that was the problem, thanks!
