### ISSUE TITLE
No permissions, not updating?!

### ISSUE THREAD

**Issue by zThana** [DRE2N/HolographicMenus#3]
Ehm, my players don't have permissions to the menu's
Aswell as, my menu's don't get updated.

My buttons don't, the title does

**Comment by Sataniel98** [comment]
Do they have the holographicmenus.menu.[name] node? How does your setup look like?

**Comment by zThana** [comment]
Well ehm, the plugin doesn't want to start up anymore...

**Comment by Sataniel98** [comment]
Plugin be like
![](http://66.media.tumblr.com/3bc4b7f9c632546127741abf3c5eb742/tumblr_no3n75ZhnC1ttu8odo1_540.gif)

**Comment by zThana** [comment]
Ehh please help, it just doesn't load...

**Comment by Sataniel98** [comment]
No stacktrace?

**Comment by zThana** [comment]
http://hastebin.com/initahoyic.vbs

**Comment by Sataniel98** [comment]
Aaaaah, you're plugmaning it. The 1.0 version has been progammed by a retarded noob, it probably contains a lot of static abuse that makes it incompatible with /reload or PlugMan.

**Comment by zThana** [comment]
So I gotta restart?

**Comment by Sataniel98** [comment]
Yeah, but there should also be an internal reload command (/hm reload)

**Comment by zThana** [comment]
Doesn't work for me

**Comment by Sataniel98** [comment]
Neither /hm reload nor a restart?

**Comment by zThana** [comment]
Restart did, /hm r didn't

**Comment by Sataniel98** [comment]
And it works, now?

**Comment by zThana** [comment]
Ehm no lol
/hm r still doesn't work

**Comment by Sataniel98** [comment]
I was referring to the initial issue :)

**Comment by zThana** [comment]
Ehm
I don't get it anymore lol

I have to restart my server if I've made changes to config

**Comment by Sataniel98** [comment]
Well, then I've probably f***ed it up :(
