### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [DRE2N/HolographicMenus#5]
logs
http://pastebin.com/vn0ic2Qb

timings
https://timings.aikar.co/v2/?id=a919e6417eb8471f99a90019c5613c07

**Comment by Sataniel98** [comment]
Possibly a setup error.

**Comment by ghost** [comment]
i not configure this plugin, i have the default config.

**Comment by zThana** [comment]
Try to restart your server, do you still get this error?

-------- Oorspronkelijk bericht --------
Van: mat41997 notifications@github.com 
Datum: 23-06-16  3:34 p.m.  (GMT+01:00) 
Aan: DRE2N/HolographicMenus HolographicMenus@noreply.github.com 
Onderwerp: Re: [DRE2N/HolographicMenus] error (#5) 

i not configure this plugin, i have the default config.

**Comment by Sataniel98** [comment]
It looks like it fails to fetch the per-player color. Does it work if you purge the data file and restart the server?
