### ISSUE TITLE
Does not see the new menu?

### ISSUE THREAD

**Issue by Teomaniaforreal** [DRE2N/HolographicMenus#7]
So, after half an hour trying to figure out the config, i thought i had it... 
but now that the main menu works, the new menu doesn't.

Also i cannot change the amount of pages in the main menu, it resets to 3 every time.
But the main problem is, is that it doesn't see the new menu... am i doing something wrong  here?

config:

main:
  pages: '3'
  texts:
    head: '%head%Main Menu - %highlight%%page% / %maxpages%'
    switch: '%head%%play% %play% %play%'
    close: '%highlight%%play%%head%Close'
    page:
      '1':
        button1: '%highlight%%play%%text%Warp info'
        button2: '%highlight%%play%%text%Warp mines'
        button3: '%highlight%%play%%text%Warp pvp'
      '2':
        button1: '%highlight%%play%%text%Warp to all Minigames!'
        button2: '%highlight%%play%%text%Warp Skywars'
        button3: '%highlight%%play%%text%Warp Spleef'
      '3':
        button1: '%highlight%%play%%text%Warp shop'
        button2: '%highlight%%play%%text%Warp Black Market'
        button3: '%highlight%%play%%text%Warp donate'
  commands:
    page:
      '1':
        button1: Warp info
        button2: Warp mines
        button3: Warp pvp
      '2':
        button1: Warp minigames
        button2: Warp skywars
        button3: Warp spleef
      '3':
        button1: Warp shop
        button2: Warp Black market
        button3: Warp donate
  positions:
    distance: 2.0
    head: 3.0
    switch: 1.2
    close: 0.6
    button1: 2.6
    button2: 2.2
    button3: 1.8
mines:
  pages: '9'
  texts:
    head: '%head%Mines - %highlight%%page% / %maxpages%'
    switch: '%head%%play% %play% %play%'
    close: '%highlight%%play%%head%Close'
    page:
      '1':
        button1: '%highlight%%play%%text%Warp A'
        button2: '%highlight%%play%%text%Warp B'
        button3: '%highlight%%play%%text%Warp C'
      '2':
        button1: '%highlight%%play%%text%Warp D'
        button2: '%highlight%%play%%text%Warp E'
        button3: '%highlight%%play%%text%Warp F'
      '3':
        button1: '%highlight%%play%%text%Warp G'
        button2: '%highlight%%play%%text%Warp H'
        button3: '%highlight%%play%%text%Warp I'
      '4':
        button1: '%highlight%%play%%text%Warp J'
        button2: '%highlight%%play%%text%Warp K'
        button3: '%highlight%%play%%text%Warp L'
      '5':
        button1: '%highlight%%play%%text%Warp M'
        button2: '%highlight%%play%%text%Warp N'
        button3: '%highlight%%play%%text%Warp O'
      '6':
        button1: '%highlight%%play%%text%Warp P'
        button2: '%highlight%%play%%text%Warp Q'
        button3: '%highlight%%play%%text%Warp R'
      '7':
        button1: '%highlight%%play%%text%Warp S'
        button2: '%highlight%%play%%text%Warp T'
        button3: '%highlight%%play%%text%Warp U'
      '8':
        button1: '%highlight%%play%%text%Warp V'
        button2: '%highlight%%play%%text%Warp W'
        button3: '%highlight%%play%%text%Warp X'
      '9':
        button1: '%highlight%%play%%text%Warp Y'
        button2: '%highlight%%play%%text%Warp Z'
        button3: '%highlight%%play%%text%Warp Prestige Mine'
  commands:
    page:
      '1':
        button1: Warp A
        button2: Warp B
        button3: Warp C
      '2':
        button1: Warp D
        button2: Warp E
        button3: Warp F
      '3':
        button1: Warp G
        button2: Warp H
        button3: Warp I
      '4':
        button1: Warp J
        button2: Warp K
        button3: Warp L
      '5':
        button1: Warp M
        button2: Warp N
        button3: Warp O
      '6':
        button1: Warp P
        button2: Warp Q
        button3: Warp R
      '7':
        button1: Warp S
        button2: Warp T
        button3: Warp U
      '8':
        button1: Warp V
        button2: Warp W
        button3: Warp X
      '9':
        button1: Warp Y
        button2: Warp Z
        button3: Warp PrestigeMine
  positions:
    distance: 2.0
    head: 3.0
    switch: 1.2
    close: 0.6
    button1: 2.6
    button2: 2.2
    button3: 1.8

**Comment by Sataniel98** [comment]
I see just three pages in your main menu config. Could you provide the config with correct indents etc?
